apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: default
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: bryguy76/nodejs-otel
        imagePullPolicy: Always
        env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://$(HOST_IP):4318"
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: "team=foo,service.name=nodejs"
        ports:
        - containerPort: 8080
          name: node

