apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol
spec:
  mode: daemonset
  hostNetwork: true
  image: otel/opentelemetry-collector-contrib
  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      resource:
        attributes:
        - key: datadog.container.tag.team
          action: upsert
          from_attribute: team
      transform:
        trace_statements:
          - context: resource
            statements:
              - set(attributes["datadog.host.use_as_metadata"], true)
      batch:
        send_batch_max_size: 100
        send_batch_size: 10
        timeout: 10s
      k8sattributes:
        passthrough: false
        auth_type: "serviceAccount"
        pod_association:
          - sources:
            - from: resource_attribute
              name: k8s.pod.ip
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.node.name
            - k8s.namespace.name
            - k8s.pod.start_time
            - k8s.replicaset.name
            - k8s.replicaset.uid
            - k8s.daemonset.name
            - k8s.daemonset.uid
            - k8s.job.name
            - k8s.job.uid
            - k8s.cronjob.name
            - k8s.statefulset.name
            - k8s.statefulset.uid
            - container.image.name
            - container.image.tag
            - container.id
            - k8s.container.name
            - container.image.name
            - container.image.tag
            - container.id
          labels:
            - tag_name: kube_app_name
              key: app.kubernetes.io/name
              from: pod
            - tag_name: kube_app_instance
              key: app.kubernetes.io/instance
              from: pod
            - tag_name: kube_app_version
              key: app.kubernetes.io/version
              from: pod
            - tag_name: kube_app_component
              key: app.kubernetes.io/component
              from: pod
            - tag_name: kube_app_part_of
              key: app.kubernetes.io/part-of
              from: pod
            - tag_name: kube_app_managed_by
              key: app.kubernetes.io/managed-by
              from: pod
      resourcedetection:
        detectors: [env, system]
        timeout: 2s
        override: false
    connectors:
      datadog/connector:
    exporters:
      datadog:
        api:
          key: <DD_API_KEY>
    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [resource, transform, batch]
          exporters: [datadog]

